name: twoandahalfdimensions
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python==3.10
  - pytorch>=2.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - conda-forge::wandb
  - conda-forge::seaborn
  - conda-forge::pandas
  - conda-forge::scikit-learn
  - conda-forge::torchmetrics
  - conda-forge::monai
  - conda-forge::opacus>=1.4
  - pip
  - pip: 
    - medmnist
    - hydra-core
    - torchio
    - PrivateModelArchitectures>=0.1.1
    - git+https://github.com/a1302z/ACSConv.git