defaults:
  - base_config
  - _self_
general:
  force_cpu: False
  log_wandb: False
data:
  name: organmnist3d
wandb: 
  project: twoandahalfdimensions
loader:
  num_workers: 0
  # prefetch_factor: 1
  pin_memory: True
model: 
  type: twop5_att
  backbone: resnet18
  in_channels: 1
  num_classes: 11
  freeze_feature_extractor: True
  feature_dim: 128
  additional_args:
    num_heads: 8
hyperparams: 
  epochs: 200
  train_bs: 256
  val_bs: 100
  test_bs: 100
  lr: 2e-3
  # overfit: 5
transforms:
  train_tf:
    RandomFlip:
      flip_probability: 0.5