defaults:
  - acs_base@_here_
  - _self_
general:
  log_images: True
  private_data: True
  output_save_folder: out/
wandb:
  project: twoandahalfdimensions
  name: pdac_acs_private
data:
  name: ct_imagefolder
  loader: monai
  base_path: ./data/PDAC_fairness
loader:
  num_workers: 16
  prefetch_factor: 4
model:
  type: acs_direct
  backbone: resnet9
  num_classes: 1
  feature_dim: 2048
  unfreeze:
    train_mode: -1
    feature_extractor: -1
    start_only_new_layers_trainable: False
hyperparams: 
  train_bs: 1
  val_bs: 2
  test_bs: 2
  grad_acc_steps: 512
transforms:
  tf_library: monai
  train_tf:
    EnsureChannelFirst:
  val_tf:
    EnsureChannelFirst:
  test_tf:
    EnsureChannelFirst:
privacy:
  use_privacy: True
  fix_model_for_privacy: True
  epsilon: 8
  delta: 1e-3
  clip_norm: 1
  accountant: gdp
