defaults:
  - att_base@_here_
  - _self_
general:
  log_images: True
  private_data: True
  output_save_folder: out/
wandb:
  project: twoandahalfdimensions
  name: pdac_att
data:
  name: ct_imagefolder
  loader: monai
  base_path: ./data/PDAC_classification
loader:
  num_workers: 16
  prefetch_factor: 8
model:
  num_classes: 1
  unfreeze:
    feature_extractor: 0
hyperparams: 
  train_bs: 2
  val_bs: 16
  test_bs: 16
  grad_acc_steps: 32
  opt_args:
    weight_decay: 1e-3
transforms:
  tf_library: monai
  train_tf:
    EnsureChannelFirst:
    tf_list:
      - RandFlip:
          prob: 0.3
          spatial_axis: 0
      - RandFlip:
          prob: 0.3
          spatial_axis: 1
    RandZoom:
      prob: 0.2
    RandAffine:
      prob: 0.2
  val_tf:
    EnsureChannelFirst:
  test_tf:
    EnsureChannelFirst:
