defaults:
  - acs_base@_here_
  - _self_
general:
  log_images: True
  private_data: True
  output_save_folder: out/
wandb:
  project: twoandahalfdimensions
  name: pdac_3d_private
data:
  name: ct_imagefolder
  loader: monai
  base_path: ./data/PDAC_classification
loader:
  num_workers: 16
  prefetch_factor: 4
model:
  type: acs_3d
  num_classes: 1
  unfreeze:
    train_mode: -1
    feature_extractor: 0
hyperparams: 
  train_bs: 2
  val_bs: 16
  test_bs: 16
  grad_acc_steps: 32
transforms:
  tf_library: monai
  train_tf:
    EnsureChannelFirst:
  val_tf:
    EnsureChannelFirst:
  test_tf:
    EnsureChannelFirst:
privacy:
  use_privacy: True
  fix_model_for_privacy: True
  epsilon: 8
  delta: 1e-3
  clip_norm: 1