defaults:
  - att_base@_here_
  - _self_
wandb:
  name: organmnist3d_att
data:
  name: organmnist3d
model: 
  num_classes: 11
  backbone: vit_b_16
  unfreeze: 
    train_mode: 0
    feature_extractor: 10000
hyperparams:
  train_bs: 4
transforms:
  train_tf:
    Resize:
      target_shape:
        - 224
        - 224
        - 224